apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-helm-upgrade
spec:
  description: Clones a git repo and upgrades the helm chart (from source)
  params:
    - name: git-repository-url
      type: string
    - name: helm-release-name
      type: string
    - name: helm-charts_dir
      type: string
    - name: helm-release-namespace
      type: string
    - name: helm-upgrade-extra-params
      type: string

  workspaces:
    - name: shared-data

  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.git-repository-url)

    - name: helm-upgrade-from-source
      runAfter: ["fetch-source"]
      taskRef:
        name: helm-upgrade-from-source
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: charts_dir
          value: $(params.helm-charts_dir)
        - name: release_name
          value: $(params.helm-release-name)
        - name: release_namespace
          value: $(params.helm-release-namespace)
        - name: upgrade_extra_params
          value: $(params.helm-upgrade-extra-params)
        - name: helm_image
          value: "alpine/helm:3.13.3" # https://github.com/helm/helm/issues/6677
